path: C:\Users\dhomi\OneDrive\Documentos\UFPA - Eng Comp\Proj Eng II\fruit-identifier\model\data
train: "train/images"
val: "val/images"

# Classes
names:
    0: rotten_apple
    1: fresh_apple
    2: rotten_banana
    3: fresh_banana
    